version: 2
updates:
  - target-branch: "main"
    package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: "scope"
    ignore:
      - dependency-name: "*"
        versions: [ "*-SNAPSHOT" ]

  - target-branch: "3.x"
    package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      include: "scope"
    ignore:
      - dependency-name: "*"
        versions: [ "*-SNAPSHOT" ]
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.ai:*"
        update-types: ["version-update:semver-major"]